language: cpp

before_install:
  - sudo apt-get install -y libarmadillo-dev python3 python3-pybind11 pybind11-dev qt5-default

addons:
  apt:
    sources: debian-sid
    update: true

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
