language: cpp

dist: xenial

before_install:
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu bionic main'
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu bionic-security main'
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu bionic-updates main'
  - sudo apt-get update
  - cat /etc/apt/sources.list
  - sudo apt-get install -y libarmadillo-dev python3 python3-pybind11 pybind11-dev qt5-default

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
