compiler: gcc
sudo: require
dist: xenial

before_install:
  - echo "before install"
  - sudo apt update

install:
  - echo "install"
  - sudo apt install ninja

after_install:
  - echo "after install"

script:
  - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DQT_QM_PATH=/opt/qt512/translations -DCMAKE_PREFIX_PATH=/opt/qt512 -DCMAKE_INSTALL_PREFIX=/usr 
  - ninja 

branches:
  except:
    - /^(?i:continuous)/
