language: cpp

dist: xenial

before_install:
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu bionic main'
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu bionic universe'
  - sudo apt-get update
  - sudo apt-get install -y python3-pybind11 pybind11-dev qt5-default libarmadillo-dev python3 

compiler:
  - gcc

before_script:
  - cd src
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
