language: cpp

dist: bionic

before_install:
  - sudo apt-
  - sudo apt-get install -y libarmadillo-dev python3 python3-pybind11 pybind11-dev qt5-default

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
