language: cpp

dist: xenial

before_install:
  - echo 'deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse' | tee --append /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - sudo apt-get install -y libarmadillo-dev python3 python3-pybind11 pybind11-dev qt5-default

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
