compiler: gcc
sudo: require
language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: windows

script:
  - |
    case "$TRAVIS_OS_NAME" in
    "linux")
      # assume a ubuntu distribution
      ./build-ubuntu.sh
      ;;
    "windows")
      echo "build windows"
      ;;
    "osx")
      echo "build osx"
      ;;
    esac

branches:
  except:
    - /^(?i:continuous)/
