compiler: gcc
sudo: require
language: cpp

jobs:
  include:
  - os: linux
    dist: xenial
  - os: windows

before_install:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
      choco uninstall -y mingw
      choco upgrade --no-progress -y msys2
      export msys2='cmd //C RefreshEnv.cmd '
      export msys2+='& set MSYS=winsymlinks:nativestrict '
      export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
      export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
      export msys2+=" -msys2 -c "\"\$@"\" --"
      $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
      ## Install more MSYS2 packages from https://packages.msys2.org/base here
      taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
      export PATH=/C/tools/msys64/mingw64/bin:$PATH
      export MAKE=mingw32-make  # so that Autotools can find it
      ;;
  esac

before_cache:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      # https://unix.stackexchange.com/a/137322/107554
      $msys2 pacman --sync --clean --noconfirm
      ;;
  esac

cache:
  directories:
  - "$HOME/AppData/Local/Temp/chocolatey"
  - "/C/tools/msys64"

script:
- |
  case "$TRAVIS_OS_NAME" in
  "linux")
    # assume a ubuntu distribution
    ./build-ubuntu.sh
    ;;
  "windows")
    $mingw64 ./build-mingw64.sh
    ;;
  "osx")
    echo "build osx not yet supported."
    ;;
  esac

after_success:
- |
  case "$TRAVIS_OS_NAME" in
  "linux")
    # assume a ubuntu distribution
    ./build/test/unit/ommpfritt_unit_test
    ;;
  "windows")
    echo "skip test on windows"
    ;;
  "osx")
    echo "skip test osx"
    ;;
  esac

deploy:
  provider: releases
  api_key:
    secure: FvwVlBt0Fgtgjom/7SFa0kR4TQVeufQc0QAF3KZOUZWPNxfu/A+0QIDXTRw3dhmZderI1QPYchgxW41ybOULzoOICHZ2eeBQfC57PAueyHNwVmK87mEKBlVy6dC7TrQNoqwJQNntA8IqcGisTLTEM31SJje5rLPfAwDfdFk1/l6uKO+cBbXx/wG3vmDuX5uz0vP4xqmwJaY8fa00cFxAydTaXAUu/hXtBGMnJBNXcQc55c20NsbHuUmTuKRixuZnUfp1rJ2L/DTDHOuqZuP7pde+CsIM2pLwVauYB5kCMpPctptNr98JXWpTX5Bx7piwyOdVyVwCoOmBiNvCd069cQQkJu3LuIWng+W0f5WHQU7YzVG/yk/XqENXo9L8bzK0xP6adsHcMz9Mzp+tUmgcnBnW8YaA/JfB5frr3dvgZ13X0iMZ2PYkXyT24LDBQajsUwSoSKvTUfDT/epXJF4zZEcSu+xizn6zHjrA1tVAUyjvCSIC7+bFcgT4NFgH2Qy4OFdpnfacmD7ZAIzRy3TY14/hLLFidoZeQj0Iwfnm12BqScGHY1Q6dqBb/vxuc3Ct9+BR1DT2VUwkxY85U+Ze9tWXBQQ0CtVnaU8omCSaUFwS0geyDmmyA0yDahnmrkY7uh1zZfvvjnuIAlCOCidtzgutd0gT9tkP2fKkwj23ejk=
  file:
    - build/ommpfritt
    - build/ommpfritt.exe
    - build/ommpfritt-0.1.0-win64.exe
    - build/ommpfritt-0.1.0-Linux.sh
  on:
    repo: pasbi/trytravis
  skip_cleanup: 'true'
