compiler: gcc
sudo: require
language: cpp

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: windows

script:
  - |
    case "$TRAVIS_OS_NAME" in
    "linux")
      # assume a ubuntu distribution
      ./build-ubuntu.sh
      ;;
    "windows")
      echo "build windows"
      choco install -y msys2
      ls /c/
      ls /c/tools/
      ls /c/tools/msys64/
      /c/tools/msys64/msys2_shell.cmd -defterm -mingw64 -no-start -full-path -here -c './hello-msys.sh'
      ;;
    "osx")
      echo "build osx"
      ;;
    esac

branches:
  except:
    - /^(?i:continuous)/
