language: cpp

dist: xenial

before_install:
  - echo 'deb http://mirror.servers.com/ubuntu/ binoic main restricted universe' | tee --append /etc/apt/sources.list
  - echo 'deb http://mirror.servers.com/ubuntu/ bionic-security main restricted universe' | tee --append /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - sudo apt-get install -y libarmadillo-dev python3 python3-pybind11 pybind11-dev qt5-default

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
